# Generated by Django 5.2 on 2025-10-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_code', models.CharField(max_length=64, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(default='pending', max_length=32)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=128, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
