# Generated by Django 5.2 on 2025-10-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
