# Generated by Django 5.2 on 2025-11-17 22:47

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_sku_fabc41_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_total_s_70556a_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_best_seller',
            new_name='has_expiry',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='max_stock',
            new_name='max_stock_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku_afe0af_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['bar_code'], name='product_bar_cod_f690e8_idx'),
        ),
    ]
