# Generated by Django 5.2 on 2025-11-18 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_last_restock_date_product_last_sold_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_payment_bfacad_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_order_i_c618ed_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_code',
            new_name='order_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('qr', 'QR Code'), ('transfer', 'Chuyển khoản'), ('debt', 'Công nợ')], default='cash', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('paid', 'Đã thanh toán'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy'), ('delete', 'Đã xóa')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order_code'], name='payment_order_c_77892e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_status_271abe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payment_transac_9ff03c_idx'),
        ),
    ]
