# Generated by Django 5.2 on 2025-09-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_barcode_product_bar_code_alter_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
