# Generated by Django 5.2 on 2025-11-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_create_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
