# Generated by Django 5.2 on 2025-09-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='user_phone_n_2e859d_idx',
            old_name='accounts_us_phone_n_613c4a_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_email_7bbb4c_idx',
            old_name='accounts_us_email_74c8d6_idx',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
