# Generated by Django 5.2 on 2025-09-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_us_phone_n_613c4a_idx_user_phone_n_2e859d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_change_pass',
            field=models.BooleanField(default=False),
        ),
    ]
