# Generated by Django 5.2 on 2025-10-26 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('debit_amount', models.DecimalField(decimal_places=5, max_digits=19)),
                ('note', models.TextField(max_length=255)),
                ('paid_amount', models.DecimalField(decimal_places=5, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=5, max_digits=19)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debit.customer')),
            ],
            options={
                'db_table': 'debit',
            },
        ),
    ]
