# Generated by Django 5.2 on 2025-10-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debit',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
