# Generated by Django 5.2 on 2025-10-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('debit_amount', models.DecimalField(decimal_places=5, max_digits=19)),
                ('note', models.TextField(max_length=255)),
                ('paid_amount', models.DecimalField(decimal_places=5, max_digits=19)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=5, max_digits=19)),
            ],
            options={
                'db_table': 'debit',
            },
        ),
    ]
